### ISSUE TITLE
Disable installation of plugin on JDK < 11

### ISSUE THREAD

**Issue by jkovalsky** [mbien/xpath-util#2]
Similarly to issue #[178](https://github.com/funfried/externalcodeformatter_for_netbeans/issues/178) in External Formatter plugin it would be good to disable installation of this xPath Util plugin on JDKs older than required version 11. Please see [this example in module manifest](https://github.com/apache/netbeans/blob/master/java/lib.nbjshell9/manifest.mf#L8) for how to do that.

**Comment by mbien** [comment]
@jkovalsky understood. Will change that in the next version. Although NetBeans doesn't really support JDK 8 anymore, the dependency check should be there anyway.

**Comment by mbien** [comment]
done
