### ISSUE TITLE
Long XPath values in xpathTextField effecting NetBeans UI layout...

### ISSUE THREAD

**Issue by DwayneParks** [mbien/xpath-util#4]
This is obviously more of a nuisance, but I wanted to report it just in case it is easy to fix and you have the time and desire to do so.  😊

When the length of the entered XPath expression value in xpathTextField becomes long, it appears to cause the layout of the NetBeans UI to change in a way that I have not seen before.  At least that is my initial guess at what is going on.

I've attached a screenshot of the situation.  A description follows:

Normally the Navigator view on the left is about 2.5 times as wide as it is in this screenshot.  When I entered a long XPath Expression like the one in the screenshot, the Navigator view automatically shrunk down to the size that is shown here.

When I try to resize it back (by grabbing the divider where the blue blob is in the screenshot, for instance), it drags to the right while I hold the mouse button down and then springs back to the width that is was before I tried to resize it.

Is there any way to make the Expression text field scroll or otherwise not force this action? (if this is indeed what is happening!  Apologies if it is something else!)

Thanks for your time and for all your work over the years on NetBeans/plugins/etc!

Dwayne

![image](https://github.com/mbien/xpath-util/assets/102323224/bc6e1d29-84ae-44ad-bc8e-61139951b23b)

**Comment by mbien** [comment]
going to take a look if this can be improved for the next update release.

Nice to hear that someone is actually using the plugin :)

**Comment by DwayneParks** [comment]
That is great news!  And yes, the plugin has been very helpful.  Much appreciated!  Thank you!

**Comment by DwayneParks** [comment]
For what it is worth, I downloaded the project and (in the "Design" view of the XPathTopComponent class) enclosed the xpathTextField component in a Scroll Pane as a quick and dirty workaround for this.  I think that the JEditorPane used doesn't shrink the view on the document back automatically when I reduce the size of the text in the field, but... it works well enough as a workaround and doesn't affect the layout of the NetBeans IDE windows anymore!

I also tweaked the code a bit to pass through the QName for the return type to the evaluate logic and added four radio buttons to the UI to select the return types that I want to use (Node Set, String, Number, and Boolean... although I could probably get by with just the first two types!).  It's not that pretty, but it was fairly easy to implement these changes to provide the functionality that I wanted.

If I ever have time this year I will try to improve and cleanup the code... and maybe provide a PR if you are interested.

![XPath Utility Screenshot 2024-02-28](https://github.com/mbien/xpath-util/assets/102323224/0672fc60-b6dc-49da-8ef7-f4fdbf18c893)

**Comment by mbien** [comment]
I did look into this too, and when I did I immediately remembered that it was not the first time I tried to fix this. Due to the editor kit, the `JEditorPane` does not quite behave like a regular `JEditorPane` used outside of NetBeans. For some reason it does only expand in width but does never shrink.

The thing is that NB uses embedded editors everywhere in various windows (e.g options) and also the editor itself obviously. So I am sure there is a way to fix this properly, I just haven't had time to get to the bottom of this.

**Comment by DwayneParks** [comment]
I see.  Yes, I have mainly worked with the "crude" text components in Swing so I know about the editor kit from seeing it in the API docs, but have no experience with it (yet).  So, I decided to stop at just getting a scroll bar on there for my purposes and not dive into the editor at this time.

I would like to learn more and dive deeper into the API, but... no time right now.  Hopefully in the future I can do so.  I definitely like what the editor brings to the situation (XML completion, etc.) and prefer it here over the more basic JTextField/JTextArea components that I am familiar with!

Thanks for just providing the plugin to play around with!  I don't know how much XPath is used in new projects, but were currently integrating into some products that date back as far as 1996 and have not changed much since 2010 or so.  :-)  It is definitely helpful to me to have the ability to query against our output data with your plugin when something is wrong with how it is being processed on their web service!

**Comment by mbien** [comment]
should be fixed in v1.5

**Comment by DwayneParks** [comment]
Awesome!!!  Thanks so much!  I really appreciate it!
